### PR TITLE
Use threading to fix fetching image in main-thread

### PR DESCRIPTION
**Pull request by davidyen1124**
Sublime Text won't block anymore when fetching datas and images.

### CODE REVIEW

**Comment by EivindArvesen** [comment]
I don't see what this solves, since it doesn't currently block, AFAIK.

From the [API reference](https://www.sublimetext.com/docs/3/api_reference.html), regarding set_async_timeout():
"Runs the callback on an alternate thread after the given delay (in milliseconds)."

The [porting guide](https://www.sublimetext.com/docs/3/porting_guide.html) has more info, specifically:
"... every API method is thread-safe. Furthermore, there are now asynchronous event handlers, to make writing non-blocking code easier..."

**Comment by davidyen1124** [comment]
- Open a file that its content is long enough to scroll.
- By choosing option `Xkcd: List`, Sublime Text won't be able to scroll until quick panel shows all the comics.

https://github.com/eivind88/xkcd/blob/master/xkcd.py#L92
I think the problem relies on `self.getComic(id)` is being executed before passing into `sublime.set_timeout_async()`.

**Comment by EivindArvesen** [comment]
I'm having a hard time reproducing this, as the list appears nearly instantaneously on my end, though I think I see a slight stutter if the current view is scrolling (e.g. by flicking touchpad or mouse wheel) while pressing enter on `Xkcd: List`

However, this same stutter was present when I tested the operation using your code.
Are you sure that this makes a difference on your end – is there a measurable difference on your machine?

**Comment by davidyen1124** [comment]
This is a small demo that I recorded.
I keep scrolling all the time, but I'm not able to scroll after selecting `Xkcd: list`.

xkcd2

**Comment by EivindArvesen** [comment]
Thank you!
This seems to be the same thing I see on my end, which is this:
original

This is what happens when i use the code you committed:
modified

I don't really understand why the manual use of threading would make a difference as the API async method supposedly does this in the background, but it certainly works!

**Comment by davidyen1124** [comment]
I see a little freeze in the first GIF. Try to make your network slower by downloading lots of stuffs, and you could see the freeze more clearly.

Thank you for the merge!
Hope we can make this plugin more and more powerful.

**Pull request merged**
